# Generated by Django 5.0.4 on 2024-04-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-nr_chosen', '-date_created']},
        ),
    ]
