# Generated by Django 5.0.4 on 2024-05-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalmanagement', '0003_alter_goal_nr_chosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='name',
            new_name='title',
        ),
    ]
