# Generated by Django 5.0.4 on 2024-07-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalmanagement', '0004_rename_name_goal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='nr_chosen',
        ),
    ]
