# Generated by Django 5.0.4 on 2024-04-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalmanagement', '0002_alter_goal_options'),
        ('sociablecreating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networker',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='networker',
            old_name='date_changed',
            new_name='date_modified',
        ),
        migrations.AlterField(
            model_name='networker',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalmanagement.goal', verbose_name='What do you want to achieve?'),
        ),
        migrations.AlterField(
            model_name='networker',
            name='search_code',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='Code used to find the networker'),
        ),
    ]
