# Generated by Django 5.0.4 on 2024-08-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(help_text='Vertel iets over je ervaringen van het contact. Voel je vrij te delen wat je wilt delen en niet te delen wat je niet wilt delen.', max_length=30000, verbose_name='Bericht'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='Anoniem', help_text='Een naam geeft al context aan een bericht. Voel je ook vrij om je naam op anoniem te houden', max_length=70, verbose_name='Je naam'),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum aangemaakt'),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum aangepast'),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='description',
            field=models.TextField(blank=True, default='Laat een bericht achter. Vertel iets over je ervaringen van je gesprek', help_text='Vrije ruimte en optioneel: Misschien heb je wel iets wat je wilt weten van anderen. Hier is de ruimte om verzoeken te doen aan degene die hier een berichtje achter laten', max_length=3000, verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='slug',
            field=models.SlugField(editable=False, max_length=8, unique=True, verbose_name='Code om de sociable te kunnen vinden'),
        ),
    ]
