# Generated by Django 5.0.4 on 2024-08-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0002_logmessage_user_alter_logmessage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmessage',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='logmessage',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='date_modified',
        ),
    ]
