# Generated by Django 5.0.4 on 2024-09-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0003_alter_logmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(help_text='Ik heb een bericht voor je achter gelaten. Leuk als je reageert, hoeft niet. Vertel iets over jouw ervaringen van ons gesprek. Nu is het aan jou om deze gespreksketen voor te zetten.', max_length=30000, verbose_name='Bericht'),
        ),
    ]
