# Generated by Django 5.0.4 on 2024-04-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0003_alter_networker_search_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networker',
            old_name='search_code',
            new_name='slug',
        ),
    ]
