# Generated by Django 5.0.4 on 2024-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0004_alter_logmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(help_text='Vertel iets over je ervaringen van het gesprek. Voel je vrij te delen wat je wilt delen en niet te delen wat je niet wilt delen.', max_length=30000, verbose_name='Bericht'),
        ),
        migrations.AlterField(
            model_name='sociable',
            name='description',
            field=models.TextField(blank=True, default='Ik heb een bericht voor je achter gelaten. Leuk als je reageert, hoeft niet. Vertel iets over jouw ervaringen van ons gesprek. Nu is het aan jou om deze gespreksketen voor te zetten.', help_text='Vrije ruimte en optioneel: Misschien heb je wel iets wat je wilt weten van anderen. Hier is de ruimte om verzoeken te doen aan degene die hier een berichtje achter laten', max_length=3000, verbose_name='Omschrijving'),
        ),
    ]
