# Generated by Django 5.0.4 on 2024-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0006_logmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum bewerkt'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum aangemaakt'),
        ),
    ]
