# Generated by Django 5.0.4 on 2024-10-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0007_logmessage_date_changed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociable',
            name='description',
        ),
    ]
