# Generated by Django 5.0.4 on 2024-04-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalmanagement', '0002_alter_goal_options'),
        ('sociablecreating', '0007_logmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='networker',
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='Philosopher', max_length=70, verbose_name='Your name'),
        ),
        migrations.CreateModel(
            name='Sociable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=8, unique=True, verbose_name='Code used to find the sociable')),
                ('description', models.CharField(max_length=300)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalmanagement.goal', verbose_name='What do you want to achieve?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User of the sociable')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='logmessage',
            name='sociable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sociablecreating.sociable'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Networker',
        ),
    ]
