# Generated by Django 5.0.4 on 2024-10-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0008_remove_sociable_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociable',
            name='date_modified',
        ),
    ]
