# Generated by Django 5.0.4 on 2024-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0008_remove_logmessage_networker_alter_logmessage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociable',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
