# Generated by Django 5.0.4 on 2024-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0009_alter_sociable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociable',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
