# Generated by Django 5.0.4 on 2024-11-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0009_remove_sociable_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='date_changed',
            field=models.DateTimeField(null=True, verbose_name='Datum bewerkt'),
        ),
    ]
