# Generated by Django 5.0.4 on 2024-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0010_alter_logmessage_date_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(help_text='Schrijf over je ervaringen van het contact. Voel je vrij te delen wat je wel en niet wilt delen.', max_length=30000, verbose_name='Bericht'),
        ),
    ]
