# Generated by Django 5.0.4 on 2024-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0011_alter_logmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(max_length=300, verbose_name='Message'),
        ),
    ]
