# Generated by Django 5.0.4 on 2024-11-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0011_alter_logmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='to_person',
            field=models.CharField(default='Anoniem', help_text='De naam aan wie dit bericht is bestemd. Dit is nodig zodat diegene zijn bericht kan terugvinden.', max_length=70, verbose_name='Aan wie?'),
        ),
    ]
