# Generated by Django 5.1.3 on 2024-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0012_logmessage_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='to_person',
            field=models.CharField(default='Anoniem', help_text='De (voor)naam aan wie dit bericht is bestemd. Dit is nodig zodat diegene zijn bericht terug kan vinden, als er meerdere ongelezen berichten zijn.', max_length=70, verbose_name='Aan wie?'),
        ),
    ]
