# Generated by Django 5.0.4 on 2024-07-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0012_alter_logmessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(max_length=30000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='Anonymous', max_length=70, verbose_name='Your name'),
        ),
    ]
