# Generated by Django 5.1.3 on 2024-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0013_alter_logmessage_to_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='to_person',
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(default='Anoniem', help_text='Een naam geeft al context aan een bericht. Voel je ook vrij om je naam op anoniem te houden', max_length=70, verbose_name='Je (voor)naam'),
        ),
    ]
