# Generated by Django 5.1.3 on 2024-12-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0015_alter_logmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='body',
            field=models.TextField(default='Hallo', help_text='Schrijf over je ervaringen. Alleen hallo wordt ook gewaardeerd', max_length=30000, verbose_name='Bericht'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(blank=True, help_text='Een naam geeft al context. Niet verplicht. Anoniem kan ook', max_length=70, verbose_name='Je (voor)naam'),
        ),
    ]
