# Generated by Django 5.1.3 on 2024-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociablecreating', '0017_sociable_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociable',
            name='number',
            field=models.IntegerField(verbose_name='Het nummer dat het aantal gecreeerd per user geeft'),
        ),
    ]
