# Generated by Django 5.1.3 on 2025-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sociablecreating", "0018_alter_sociable_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociable",
            name="number",
            field=models.IntegerField(
                verbose_name="De hoeveelste sociable van de user geeft"
            ),
        ),
    ]
