# Generated by Django 5.1.3 on 2025-08-18 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sociablecreating", "0019_alter_sociable_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logmessage",
            name="author",
        ),
        migrations.RemoveField(
            model_name="logmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="sociable",
            name="number",
        ),
        migrations.RemoveField(
            model_name="sociable",
            name="owner",
        ),
    ]
