# Generated by Django 5.1.3 on 2025-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreetActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Naam van de activiteit"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, verbose_name="Beschrijving van de activiteit"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("invite", "Uitnodigen"), ("approach", "Aanspreken")],
                        default="invite",
                        max_length=10,
                        verbose_name="Methode van benadering",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=200,
                        verbose_name="Kernvraag, waarmee je de ander uitnodigt of aanspreekt",
                    ),
                ),
                (
                    "supplies",
                    models.TextField(
                        max_length=300, verbose_name="Benodigdheden voor de activiteit"
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="Moeilijkheidsgraad (1-5)",
                    ),
                ),
                (
                    "chance",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="Kans op contact (1-5)",
                    ),
                ),
                (
                    "extension",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        verbose_name="Uitbreiding of variatie op de activiteit",
                    ),
                ),
                (
                    "blog",
                    models.URLField(
                        blank=True,
                        verbose_name="Link naar een blogpost over de activiteit",
                    ),
                ),
                (
                    "literature",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Relevante literatuur"
                    ),
                ),
                (
                    "needHelp",
                    models.BooleanField(default=True, verbose_name="Experimenteel"),
                ),
            ],
        ),
    ]
