# Generated by Django 5.1.3 on 2025-10-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreetActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Naam van de activiteit"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, verbose_name="Beschrijving van de activiteit"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("invite", "Uitnodigen"),
                            ("approach", "Aanspreken"),
                            ("both", "Beide"),
                        ],
                        default="invite",
                        max_length=10,
                        verbose_name="Methode van benadering",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        max_length=200,
                        verbose_name="Kernvraag, waarmee je de ander uitnodigt of aanspreekt",
                    ),
                ),
                (
                    "supplies",
                    models.TextField(
                        max_length=300, verbose_name="Benodigdheden voor de activiteit"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Naam van de tag"
                    ),
                ),
                (
                    "nvc_category",
                    models.CharField(
                        choices=[
                            ("needs", "behoeften"),
                            ("feelings_fulfilled", "gevoelens bij vervulde behoeften"),
                            (
                                "feelings_unfulfilled",
                                "gevoelens bij onvervulde behoeften",
                            ),
                            ("other", "anders"),
                        ],
                        default="needs",
                        max_length=25,
                        verbose_name="Behoefte of gevoel",
                    ),
                ),
                (
                    "maintag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selecteer een hoofdtag als dit een subtag is.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtags",
                        to="streetactivity.tag",
                        verbose_name="Hoofdtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["nvc_category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="Beschrijf de ervaring in maximaal 1000 karakters",
                        max_length=1000,
                        verbose_name="Verslag van de ervaring",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="Link naar een blog of andere informatie (optioneel)",
                        null=True,
                        verbose_name="Externe link naar meer informatie",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("pioneer", "pionierservaring"),
                            ("intermediate", "overgangservaring"),
                            ("climax", "climaxervaring"),
                        ],
                        default="pioneer",
                        max_length=15,
                        verbose_name="Fase van de ervaring",
                    ),
                ),
                (
                    "from_practitioner",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is deze ervaring van een beoefenaar?",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="streetactivity.streetactivity",
                        verbose_name="Gerelateerde activiteit",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="experiences",
                        to="streetactivity.tag",
                        verbose_name="Tags voor deze ervaring",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ervaring",
                "verbose_name_plural": "Ervaringen",
                "ordering": ["-date_created"],
                "indexes": [
                    models.Index(
                        fields=["-date_created"], name="streetactiv_date_cr_d9c0c7_idx"
                    ),
                    models.Index(fields=["fase"], name="streetactiv_fase_c3d67d_idx"),
                    models.Index(
                        fields=["from_practitioner"],
                        name="streetactiv_from_pr_b6f33b_idx",
                    ),
                ],
            },
        ),
    ]
