# Generated by Django 5.1.3 on 2025-10-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streetactivity",
            options={
                "ordering": ["name"],
                "verbose_name": "Straatactiviteit",
                "verbose_name_plural": "Straatactiviteiten",
            },
        ),
        migrations.AlterField(
            model_name="experience",
            name="from_practitioner",
            field=models.BooleanField(
                default=True, verbose_name="Is deze ervaring van een beoefenaar?"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="nvc_category",
            field=models.CharField(
                choices=[
                    ("needs", "Behoeften"),
                    ("feelings_fulfilled", "Gevoelens bij vervulde behoeften"),
                    ("feelings_unfulfilled", "Gevoelens bij onvervulde behoeften"),
                    ("other", "Anders"),
                ],
                default="needs",
                max_length=25,
                verbose_name="Behoefte of gevoel",
            ),
        ),
    ]
