# Generated by Django 5.1.3 on 2025-10-06 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streetactivity",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="streetactivity",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
