# Generated by Django 5.2.7 on 2025-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="report",
            field=models.TextField(
                blank=True,
                help_text="Beschrijf de ervaring in maximaal 1000 karakters",
                max_length=3500,
                verbose_name="Verslag van de ervaring",
            ),
        ),
    ]
