# Generated by Django 5.1.3 on 2025-10-14 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0002_streetactivity_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streetactivity",
            options={"ordering": ["name"]},
        ),
    ]
