# Generated by Django 5.1.3 on 2025-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0002_alter_streetactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streetactivity",
            name="description",
            field=models.TextField(
                max_length=3000, verbose_name="Beschrijving van de activiteit"
            ),
        ),
    ]
