# Generated by Django 5.2.7 on 2025-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0002_alter_experience_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="fase",
            field=models.CharField(
                choices=[
                    ("insecure", "onzeker"),
                    ("inbetween", "tussenin"),
                    ("confident", "zelfverzekerd"),
                ],
                default="insecure",
                max_length=15,
                verbose_name="Zelfverzekerdheid",
            ),
        ),
    ]
