# Generated by Django 5.1.3 on 2025-10-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0003_alter_streetactivity_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streetactivity",
            name="blog",
        ),
        migrations.RemoveField(
            model_name="streetactivity",
            name="literature",
        ),
        migrations.CreateModel(
            name="ExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titel van de referentie"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Wat is de relatie met deze straatactiviteit?",
                        max_length=500,
                        verbose_name="Beschrijving of samenvatting",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL naar blog, video, artikel, etc. Niet verplicht voor boeken/theorie.",
                        verbose_name="Link (optioneel)",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Bijv: persoonlijke ervaring, boek, onderzoek, theorie, inspiratie...",
                        max_length=100,
                        verbose_name="Soort referentie (optioneel)",
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Ingediend door (optioneel)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_references",
                        to="streetactivity.streetactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Externe Referentie",
                "verbose_name_plural": "Externe Referenties",
                "ordering": ["-created_at"],
            },
        ),
    ]
