# Generated by Django 5.1.3 on 2025-10-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0004_remove_streetactivity_blog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SWOTElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("S", "Sterke punt"),
                            ("W", "Zwakke punt"),
                            ("O", "Kans"),
                            ("T", "Bedreiging"),
                        ],
                        max_length=1,
                    ),
                ),
                ("formulation", models.TextField(max_length=500)),
                ("rating", models.FloatField(default=0.0)),
                ("total_votes", models.IntegerField(default=0)),
                ("needs_voting", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "street_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swot_elements",
                        to="streetactivity.streetactivity",
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-date_created"],
            },
        ),
        migrations.CreateModel(
            name="SWOTVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formulation", models.TextField(max_length=500)),
                ("votes_for", models.IntegerField(default=0)),
                ("votes_against", models.IntegerField(default=0)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "swot_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="streetactivity.swotelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_current", "-votes_for", "-created_at"],
            },
        ),
    ]
