# Generated by Django 5.1.3 on 2025-10-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0005_swotelement_swotversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="swotelement",
            options={"ordering": ["-recognition_count", "-date_created"]},
        ),
        migrations.RemoveField(
            model_name="swotelement",
            name="date_modified",
        ),
        migrations.RemoveField(
            model_name="swotelement",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="swotelement",
            name="total_votes",
        ),
        migrations.AddField(
            model_name="swotelement",
            name="alternative_formulation",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="swotelement",
            name="recognition_count",
            field=models.IntegerField(default=0, verbose_name="Aantal herkenningen"),
        ),
        migrations.AddField(
            model_name="swotelement",
            name="votes_alternative",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="swotelement",
            name="votes_current",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="swotelement",
            name="street_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streetactivity.streetactivity",
            ),
        ),
        migrations.CreateModel(
            name="SWOTHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_formulation", models.TextField(max_length=500)),
                ("new_formulation", models.TextField(max_length=500)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "swot_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streetactivity.swotelement",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.DeleteModel(
            name="SWOTVersion",
        ),
    ]
