# Generated by Django 5.2.7 on 2025-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0005_alter_experience_fase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="fase",
            field=models.CharField(
                choices=[
                    ("pioneer", "onzeker"),
                    ("intermediate", "tussenin"),
                    ("climax", "zelfverzekerd"),
                ],
                default="pioneer",
                max_length=15,
                verbose_name="Zelfverzekerdheid",
            ),
        ),
    ]
