# Generated by Django 5.1.3 on 2025-10-19 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0006_alter_swotelement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swotelement",
            name="street_activity",
        ),
        migrations.RemoveField(
            model_name="swothistory",
            name="swot_element",
        ),
        migrations.RemoveField(
            model_name="streetactivity",
            name="chance",
        ),
        migrations.RemoveField(
            model_name="streetactivity",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="streetactivity",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="streetactivity",
            name="needHelp",
        ),
        migrations.DeleteModel(
            name="ExternalReference",
        ),
        migrations.DeleteModel(
            name="SWOTElement",
        ),
        migrations.DeleteModel(
            name="SWOTHistory",
        ),
    ]
