# Generated by Django 5.2.7 on 2025-11-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0006_alter_experience_fase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="report",
            field=models.TextField(
                blank=True,
                help_text="Beschrijf wat zich aandiende in maximaal 3500 karakters",
                max_length=3500,
                verbose_name="Wat voelde je? Wat ging er in je om?",
            ),
        ),
    ]
