# Generated by Django 5.2.7 on 2025-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0007_alter_experience_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="external_link",
        ),
        migrations.AddField(
            model_name="experience",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="3 woorden die je moment samenvatten, gescheiden door komma's",
                max_length=200,
                verbose_name="Kernwoorden",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
