# Generated by Django 5.1.3 on 2025-10-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0007_remove_swotelement_street_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streetactivity",
            name="method",
            field=models.CharField(
                choices=[
                    ("invite", "Uitnodigen"),
                    ("approach", "Aanspreken"),
                    ("both", "Beide"),
                ],
                default="invite",
                max_length=10,
                verbose_name="Methode van benadering",
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        max_length=1000, verbose_name="Verslag van de ervaring"
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Externe link naar meer informatie, zoals een blog (optioneel)",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("pioneer", "pionierservaring"),
                            ("intermediate", "overgangservaring"),
                            ("climax", "climaxervaring"),
                        ],
                        default="pioneer",
                        max_length=15,
                        verbose_name="Fase van de ervaring",
                    ),
                ),
                (
                    "fromPractitioner",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is deze ervaring van een beoefenaar?",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="streetactivity.streetactivity",
                        verbose_name="Gerelateerde activiteit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Naam van de tag"
                    ),
                ),
                (
                    "experiences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="streetactivity.experience",
                        verbose_name="Ervaringen geassocieerd met deze tag",
                    ),
                ),
            ],
        ),
    ]
