# Generated by Django 5.1.3 on 2025-10-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0008_alter_streetactivity_method_experience_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Ervaring",
                "verbose_name_plural": "Ervaringen",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["nvc_category", "name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="fromPractitioner",
            new_name="from_practitioner",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="experiences",
        ),
        migrations.AddField(
            model_name="experience",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="experiences",
                to="streetactivity.tag",
                verbose_name="Tags voor deze ervaring",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, verbose_name="Beschrijving van de tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="main_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecteer een hoofdtag als dit een subtag is.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_tags",
                to="streetactivity.tag",
                verbose_name="Hoofdtag",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="nvc_category",
            field=models.CharField(
                choices=[
                    ("needs", "behoeften"),
                    ("feelings fulfilled", "gevoelens bij vervulde behoeften"),
                    ("feelings unfulfilled", "gevoelens bij onvervulde behoeften"),
                    ("other", "anders"),
                ],
                default="needs",
                max_length=25,
                verbose_name="Behoefte of gevoel",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="external_link",
            field=models.URLField(
                blank=True,
                help_text="Link naar een blog of andere informatie (optioneel)",
                null=True,
                verbose_name="Externe link naar meer informatie",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="report",
            field=models.TextField(
                blank=True,
                help_text="Beschrijf de ervaring in maximaal 1000 karakters",
                max_length=1000,
                verbose_name="Verslag van de ervaring",
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["-date_created"], name="streetactiv_date_cr_d9c0c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(fields=["fase"], name="streetactiv_fase_c3d67d_idx"),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["from_practitioner"], name="streetactiv_from_pr_b6f33b_idx"
            ),
        ),
    ]
