# Generated by Django 5.2.7 on 2025-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0008_remove_experience_tags_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="experience",
            name="streetactiv_fase_c3d67d_idx",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="fase",
            new_name="confidence_level",
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["confidence_level"], name="streetactiv_confide_643470_idx"
            ),
        ),
    ]
