# Generated by Django 5.2.7 on 2025-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "streetactivity",
            "0009_remove_experience_streetactiv_fase_c3d67d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="confidence_level",
            field=models.CharField(
                choices=[
                    ("insecure", "onzeker"),
                    ("intermediate", "tussenin"),
                    ("climax", "zelfverzekerd"),
                ],
                default="insecure",
                max_length=15,
                verbose_name="Zelfverzekerdheid",
            ),
        ),
    ]
