# Generated by Django 5.2.7 on 2025-12-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0011_alter_experience_confidence_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="Beschrijf wat zich aandiende in maximaal 3500 karakters",
                        max_length=3500,
                        verbose_name="Wat voelde je? Wat ging er in je om?",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("pioneer", "onzeker"),
                            ("intermediate", "tussenin"),
                            ("climax", "zelfverzekerd"),
                        ],
                        default="pioneer",
                        max_length=15,
                        verbose_name="Zelfverzekerdheid",
                    ),
                ),
                (
                    "from_practitioner",
                    models.BooleanField(
                        default=True,
                        verbose_name="Is deze ervaring van een beoefenaar?",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="3 woorden die je moment samenvatten, gescheiden door komma's",
                        max_length=200,
                        verbose_name="Kernwoorden",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moments",
                        to="streetactivity.streetactivity",
                        verbose_name="Gerelateerde activiteit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ervaring",
                "verbose_name_plural": "Ervaringen",
                "ordering": ["-date_created"],
            },
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(
                fields=["-date_created"], name="streetactiv_date_cr_90f158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(
                fields=["confidence_level"], name="streetactiv_confide_273b3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(
                fields=["from_practitioner"], name="streetactiv_from_pr_e2e967_idx"
            ),
        ),
    ]
