# Generated by Django 5.2.7 on 2025-12-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0011_alter_experience_confidence_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Korte bemoediging of coaching tip (max 150 tekens)",
                        max_length=150,
                        verbose_name="Bemoedigend bericht",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_reactions",
                        to="streetactivity.experience",
                        verbose_name="Bij moment",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Van gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnerreactie",
                "verbose_name_plural": "Partnerreacties",
                "ordering": ["created_at"],
                "unique_together": {("from_user", "experience")},
            },
        ),
    ]
