# Generated by Django 5.2.7 on 2025-12-16 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0012_moment_delete_experience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moment",
            options={
                "ordering": ["order", "-date_created"],
                "verbose_name": "Moment",
                "verbose_name_plural": "Momenten",
            },
        ),
        migrations.AddField(
            model_name="moment",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Volgorde van het moment binnen de ervaring",
                verbose_name="Volgorde",
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Is voltooid?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Speler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ervaring",
                "verbose_name_plural": "Ervaringen",
                "ordering": ["-date_created"],
            },
        ),
        migrations.AddField(
            model_name="moment",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moments",
                to="streetactivity.experience",
                verbose_name="Gerelateerde ervaring",
            ),
        ),
        migrations.AddIndex(
            model_name="moment",
            index=models.Index(fields=["order"], name="streetactiv_order_aaa004_idx"),
        ),
    ]
