# Generated by Django 5.2.7 on 2025-12-02 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0012_reaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reaction",
            new_name="PartnerReaction",
        ),
    ]
