# Generated by Django 5.2.7 on 2025-12-04 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0013_rename_reaction_partnerreaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartnerReaction",
        ),
    ]
