# Generated by Django 5.2.7 on 2025-12-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetactivity', '0014_convert_confidence_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='confidence_level',
            field=models.IntegerField(choices=[(0, 'onzeker'), (1, 'tussenin'), (2, 'zelverzekerd')], default=0, verbose_name='Zelfverzekerdheid'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='keywords',
            field=models.CharField(blank=True, help_text="3 woorden, gescheiden door komma's", max_length=200, verbose_name='Kernwoorden'),
        ),
    ]
