# Generated by Django 5.2.7 on 2026-01-07 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0015_alter_moment_confidence_level_alter_moment_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="is_complete",
        ),
    ]
