# Generated by Django 5.2.7 on 2026-01-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0016_remove_experience_is_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moments",
                to="streetactivity.streetactivity",
                verbose_name="Gerelateerde activiteit",
            ),
        ),
    ]
