# Generated by Django 5.2.7 on 2026-02-12 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0017_alter_moment_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moment",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Moment",
                "verbose_name_plural": "Momenten",
            },
        ),
    ]
