# Generated by Django 5.2.7 on 2026-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0018_alter_moment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="report",
            field=models.TextField(
                blank=True,
                help_text="Beschrijf wat zich aandiende in maximaal 367 karakters",
                max_length=367,
                verbose_name="Wat voelde je? Wat ging er in je om?",
            ),
        ),
    ]
