# Generated by Django 5.2.7 on 2026-02-16 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0019_alter_moment_report"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moment",
            name="streetactiv_order_aaa004_idx",
        ),
        migrations.RemoveField(
            model_name="moment",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="moment",
            name="order",
        ),
    ]
