# Generated by Django 5.2.7 on 2026-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0020_remove_moment_streetactiv_order_aaa004_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="confidence_level",
            field=models.IntegerField(
                choices=[(0, "onzeker"), (1, "tussenin"), (2, "zelfverzekerd")],
                default=0,
                verbose_name="Zelfverzekerdheid",
            ),
        ),
    ]
