# Generated by Django 5.2.7 on 2026-02-26 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0021_alter_moment_confidence_level"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moment",
            name="streetactiv_from_pr_e2e967_idx",
        ),
        migrations.RemoveField(
            model_name="moment",
            name="from_practitioner",
        ),
    ]
