# Generated by Django 5.2.7 on 2026-02-26 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "streetactivity",
            "0022_remove_moment_streetactiv_from_pr_e2e967_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moment",
            name="experience",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
    ]
