# Generated by Django 5.2.7 on 2026-02-27 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0023_remove_moment_experience_delete_experience"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moment",
            name="streetactiv_confide_273b3c_idx",
        ),
        migrations.RemoveField(
            model_name="moment",
            name="confidence_level",
        ),
    ]
