# Generated by Django 5.2.7 on 2026-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "streetactivity",
            "0024_remove_moment_streetactiv_confide_273b3c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moment",
            name="word",
            field=models.CharField(
                blank=True,
                help_text="Welk woord past bij dit moment?",
                max_length=100,
                verbose_name="Eén woord",
            ),
        ),
    ]
