# Generated by Django 5.2.7 on 2026-03-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0026_moment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streetactivity",
            options={
                "ordering": ["name"],
                "verbose_name": "straatspel",
                "verbose_name_plural": "Straatspellen",
            },
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="description",
            field=models.TextField(
                max_length=3000, verbose_name="Beschrijving van het spel"
            ),
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Naam van het spel"),
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="supplies",
            field=models.TextField(
                max_length=300, verbose_name="Benodigdheden voor het spel"
            ),
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="Welk woord past bij dit moment?",
                        max_length=100,
                        verbose_name="Eén woord",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="streetactivity.streetactivity",
                        verbose_name="Gerelateerde activiteit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Speler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Woord",
                "verbose_name_plural": "Woorden",
                "ordering": ["-date_created"],
            },
        ),
        migrations.DeleteModel(
            name="Moment",
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["-date_created"], name="streetactiv_date_cr_26728b_idx"
            ),
        ),
    ]
