# Generated by Django 5.2.7 on 2026-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0027_alter_streetactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(
                help_text="Welk woord past bij dit moment?",
                max_length=100,
                null=True,
                verbose_name="Eén woord",
            ),
        ),
    ]
