# Generated by Django 5.2.7 on 2026-03-03 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0028_alter_word_word"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="word",
            name="streetactiv_date_cr_26728b_idx",
        ),
        migrations.AddField(
            model_name="word",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(
                default="hello",
                help_text="Welk woord past bij dit moment?",
                max_length=100,
                verbose_name="Eén woord",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["user", "date_created"], name="streetactiv_user_id_71d98a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["activity", "date_created"],
                name="streetactiv_activit_b6b165_idx",
            ),
        ),
    ]
