# Generated by Django 5.2.7 on 2026-03-05 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0029_remove_word_streetactiv_date_cr_26728b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="word",
            name="date_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
