# Generated by Django 5.2.7 on 2026-03-10 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0030_alter_word_date_created_alter_word_date_modified"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="word",
            name="streetactiv_user_id_71d98a_idx",
        ),
        migrations.RemoveField(
            model_name="word",
            name="user",
        ),
    ]
