# Generated by Django 5.2.7 on 2026-07-23 08:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0031_remove_word_streetactiv_user_id_71d98a_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reflection",
                    models.CharField(
                        help_text="Welke reflectie past bij dit moment?",
                        max_length=1000,
                        verbose_name="Reflectie over het spel",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="streetactivity.streetactivity",
                        verbose_name="Gerelateerde activiteit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflectie",
                "verbose_name_plural": "Reflecties",
                "ordering": ["-date_created"],
            },
        ),
        migrations.DeleteModel(
            name="Word",
        ),
        migrations.AddIndex(
            model_name="reflection",
            index=models.Index(
                fields=["activity", "date_created"],
                name="streetactiv_activit_9f65e5_idx",
            ),
        ),
    ]
