# Generated by Django 5.2.7 on 2026-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0032_reflection_delete_word_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reflection",
            name="context",
        ),
        migrations.AlterField(
            model_name="reflection",
            name="reflection",
            field=models.CharField(
                help_text="Hoe heb je het doen van dit spel ervaren?",
                max_length=1000,
                verbose_name="Reflectie over het spel",
            ),
        ),
    ]
