# Generated by Django 5.2.7 on 2026-08-06 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0033_remove_reflection_context_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreetActivityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a photo of the street activity (JPG, JPEG, or PNG).",
                        upload_to="street_activity_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the photo was uploaded.",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="The street activity this photo belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="streetactivity.streetactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Street Activity Photo",
                "verbose_name_plural": "Street Activity Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
