# Generated by Django 5.2.7 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0034_streetactivityphoto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streetactivity",
            options={
                "ordering": ["name"],
                "verbose_name": "straatactiviteit",
                "verbose_name_plural": "Straatactiviteiten",
            },
        ),
        migrations.AlterField(
            model_name="reflection",
            name="reflection",
            field=models.CharField(
                help_text="Hoe heb je het doen van deze activiteit ervaren?",
                max_length=1000,
                verbose_name="Reflectie over de activiteit",
            ),
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="description",
            field=models.TextField(
                max_length=3000, verbose_name="Beschrijving van de activiteit"
            ),
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Naam van deze activiteit"
            ),
        ),
        migrations.AlterField(
            model_name="streetactivity",
            name="supplies",
            field=models.TextField(
                max_length=300, verbose_name="Benodigdheden voor de activiteit"
            ),
        ),
    ]
