# Generated by Django 5.2.7 on 2026-09-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0035_alter_streetactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reflection",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Reflection",
                "verbose_name_plural": "Reflections",
            },
        ),
        migrations.AddField(
            model_name="reflection",
            name="author_profile_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the author's profile.",
                null=True,
                verbose_name="Profile URL",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="author_username",
            field=models.CharField(
                blank=True,
                help_text="The username of the author of the reflection.",
                max_length=255,
                null=True,
                verbose_name="Username",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="hashtags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of hashtags in the reflection.",
                verbose_name="Hashtags",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="URL of an image or video associated with the reflection.",
                null=True,
                verbose_name="Media URL",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="The platform where the reflection originated (e.g., Mastodon, Bluesky).",
                max_length=20,
                null=True,
                verbose_name="Platform",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="post_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the original post.",
                null=True,
                verbose_name="Post URL",
            ),
        ),
        migrations.AddField(
            model_name="reflection",
            name="timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="When the reflection was shared.",
                null=True,
                verbose_name="Date and time of the post",
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reflections",
                to="streetactivity.streetactivity",
                verbose_name="Related activity",
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="reflection",
            field=models.CharField(
                help_text="Hoe heb je het doen van deze activiteit ervaren?",
                max_length=1000,
                verbose_name="Reflection about the activity",
            ),
        ),
        migrations.AddIndex(
            model_name="reflection",
            index=models.Index(
                fields=["platform", "timestamp"], name="streetactiv_platfor_5cdbcb_idx"
            ),
        ),
    ]
