# Generated by Django 5.2.7 on 2026-09-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0036_alter_reflection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reflection",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="De unieke ID van de post op het externe platform (bijv. Mastodon).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Externe ID",
            ),
        ),
    ]
