# Generated by Django 5.2.7 on 2026-09-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0037_reflection_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reflection",
            name="reflection",
            field=models.TextField(
                help_text="Hoe heb je het doen van deze activiteit ervaren?",
                max_length=1000,
                verbose_name="Reflection about the activity",
            ),
        ),
    ]
