# Generated by Django 5.2.7 on 2026-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0038_alter_reflection_reflection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reflection",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique ID of the post on the external platform.",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="platform",
            field=models.CharField(
                blank=True,
                help_text="The platform where the reflection originated.",
                max_length=20,
                null=True,
                verbose_name="Platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("platform", "external_id"),
                name="unique_external_post_per_platform",
            ),
        ),
    ]
