# Generated by Django 5.2.7 on 2026-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streetactivity", "0039_alter_reflection_external_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reflection",
            name="streetactiv_activit_9f65e5_idx",
        ),
        migrations.RemoveField(
            model_name="reflection",
            name="activity",
        ),
        migrations.AlterField(
            model_name="reflection",
            name="reflection",
            field=models.TextField(
                help_text="Hoe heb je het spontane contact ervaren?",
                max_length=1000,
                verbose_name="Reflectie",
            ),
        ),
        migrations.AddIndex(
            model_name="reflection",
            index=models.Index(
                fields=["date_created"], name="streetactiv_date_cr_db77a7_idx"
            ),
        ),
    ]
