# Generated by Django 5.2.7 on 2026-10-07 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "streetactivity",
            "0040_remove_reflection_streetactiv_activit_9f65e5_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="StreetActivityPhoto",
        ),
    ]
