# Generated by Django 5.1.3 on 2025-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="icon",
        ),
        migrations.AddField(
            model_name="persona",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
