# Generated by Django 5.2.7 on 2025-10-30 15:59

import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="portrait",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=persona.models.persona_portrait_path,
                verbose_name="Portret foto",
            ),
        ),
    ]
