# Generated by Django 5.1.3 on 2025-10-29 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="text",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="icon",
        ),
        migrations.AddField(
            model_name="persona",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="persona",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reaction",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
