# Generated by Django 5.1.3 on 2025-10-09 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0002_remove_persona_icon_persona_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="persona",
            name="name",
        ),
        migrations.AddField(
            model_name="persona",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="persona",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reaction",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
