# Generated by Django 5.1.3 on 2025-10-13 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0003_alter_problem_options_alter_reaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={},
        ),
        migrations.RemoveField(
            model_name="problem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="order",
        ),
    ]
