# Generated by Django 5.1.3 on 2025-10-14 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0005_problem_date_added_reaction_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-date_added"]},
        ),
    ]
