# Generated by Django 5.1.3 on 2025-10-29 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0006_alter_problem_options_alter_reaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="reaction",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="persona",
            old_name="created_at",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="persona",
            old_name="updated_at",
            new_name="date_modified",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="date_added",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="date_added",
            new_name="date_created",
        ),
    ]
