# Generated by Django 5.1.3 on 2025-10-29 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0007_alter_problem_options_alter_reaction_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="text",
            new_name="description",
        ),
    ]
