from django.urls import path
from . import views

urlpatterns = [
    path("",
         views.StreetActivityListView.as_view(),
         name="streetactivity-list"),
    path("info/<int:pk>/",
         views.StreetActivityDetailView.as_view(),
         name="streetactivity-detail"),
    path("nieuw/",
         views.StreetActivityCreateView.as_view(),
         name="create-streetactivity"),
    path("update/<int:pk>/",
         views.StreetActivityUpdateView.as_view(),
         name="update-streetactivity"),
    path("delete/<int:pk>/",
         views.StreetActivityDeleteView.as_view(),
         name="delete-streetactivity"),

     path("ervaringen/",
         views.ExperienceListView.as_view(),
         name="experience-list"),
     path("ervaring/<int:pk>/",
         views.ExperienceDetailView.as_view(),
         name="experience-detail"),
     path("<int:pk>/ervaring/nieuw/",
          views.ExperienceCreateView.as_view(),
          name="create-experience"),

     path("tags/",
         views.TagListView.as_view(),
         name="tag-list"),
     path("tag/nieuw/",
           views.TagCreateView.as_view(),
           name="create-tag"),
     path("tag/<int:pk>/",
          views.TagDetailView.as_view(),
          name="tag-detail"),
]
