# Generated by Django 5.0.4 on 2024-09-13 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_description_for_code',
            field=models.TextField(blank=True, help_text='Vul deze in als je je eigen standaard omschrijving wilt gebruiken voor codes', max_length=3000, verbose_name='Omschrijving voor codes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
