# Generated by Django 5.2.7 on 2025-11-22 09:30

import django.utils.timezone
import usermanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=usermanagement.models.profile_image_path,
                verbose_name="Profiel foto",
            ),
        ),
    ]
