# Generated by Django 5.2.7 on 2025-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0002_profile_date_created_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="xp",
            field=models.IntegerField(default=0, verbose_name="De behaalde xp"),
        ),
        migrations.AddField(
            model_name="profile",
            name="xp_next_lvl",
            field=models.IntegerField(
                default=75, verbose_name="De benodigde xp voor het volgende level"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="xp_start",
            field=models.IntegerField(
                default=0, verbose_name="De xp waarmee is gestart in dit level"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lvl",
            field=models.IntegerField(default=1),
        ),
    ]
