# Generated by Django 5.0.4 on 2024-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_profile_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp_needed',
            field=models.IntegerField(default=1, verbose_name='De benodigde xp voor het volgende level'),
        ),
    ]
