# Generated by Django 5.2.7 on 2025-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "usermanagement",
            "0003_profile_xp_profile_xp_next_lvl_profile_xp_start_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="xp_percentage_of_progress",
            field=models.IntegerField(
                default=0, verbose_name="Percentage van de xp voortgang tijdens dit lvl"
            ),
        ),
    ]
