# Generated by Django 5.0.4 on 2024-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_profile_xp_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='xp_needed',
            new_name='xp',
        ),
        migrations.AddField(
            model_name='profile',
            name='xp_next_lvl',
            field=models.IntegerField(default=1, verbose_name='De benodigde xp voor het volgende level'),
        ),
    ]
