# Generated by Django 5.2.7 on 2025-12-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0004_profile_xp_percentage_of_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profiel", "verbose_name_plural": "Profielen"},
        ),
        migrations.AddField(
            model_name="profile",
            name="is_open_for_partnerships",
            field=models.BooleanField(
                default=False,
                help_text="Andere gebruikers kunnen je uitnodigen als straatpartner",
                verbose_name="Sta open voor nieuwe partnerschappen",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_moments_to_partners",
            field=models.BooleanField(
                default=True, verbose_name="Toon mijn momenten aan mijn straatpartners"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_online_status",
            field=models.BooleanField(default=False, verbose_name="Toon online status"),
        ),
    ]
