# Generated by Django 5.2.7 on 2026-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0004_profile_xp_percentage_of_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="xp_next_lvl",
            field=models.IntegerField(
                default=100, verbose_name="De benodigde xp voor het volgende level"
            ),
        ),
    ]
