# Generated by Django 5.0.4 on 2024-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_rename_xp_needed_profile_xp_gained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp_start_lvl',
            field=models.IntegerField(default=0, verbose_name='De start xp van het level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='De benodigde xp voor het volgende level'),
        ),
    ]
