# Generated by Django 5.2.7 on 2026-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usermanagement", "0005_alter_profile_xp_next_lvl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="lvl",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="xp",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="xp_next_lvl",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="xp_percentage_of_progress",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="xp_start",
        ),
    ]
