# Generated by Django 5.0.4 on 2024-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_profile_xp_start_lvl_alter_profile_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='De behaalde xp'),
        ),
    ]
