# Generated by Django 5.0.4 on 2024-10-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_alter_profile_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_description_for_code',
        ),
    ]
