# Generated by Django 5.2.7 on 2026-09-24 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weaktie", "0002_whereabout_delete_gettogether"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whereabout",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
