# Generated by Django 5.2.7 on 2026-09-27 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weaktie", "0004_alter_whereabout_options_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whereabout",
            options={
                "ordering": ["-when"],
                "verbose_name": "gelegenheid",
                "verbose_name_plural": "gelegenheden",
            },
        ),
        migrations.RenameField(
            model_name="whereabout",
            old_name="date",
            new_name="when",
        ),
    ]
