# Generated by Django 5.2.7 on 2026-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weaktie", "0005_alter_whereabout_options_rename_date_whereabout_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
