# Generated by Django 5.1.3 on 2025-08-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=8,
                        unique=True,
                        verbose_name="Code om de chatroom te kunnen vinden",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum aangemaakt"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Een naam geeft al context. Niet verplicht. Anoniem kan ook",
                        max_length=70,
                        verbose_name="Je (voor)naam",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Hallo",
                        help_text="Schrijf over je ervaringen. Alleen hallo wordt ook gewaardeerd",
                        max_length=30000,
                        verbose_name="Bericht",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum aangemaakt"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(null=True, verbose_name="Datum bewerkt"),
                ),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatroomcreating.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
