# Generated by Django 5.2.7 on 2025-10-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Code om de chatroom te kunnen vinden",
                    ),
                ),
                ("secret_key", models.CharField(editable=False, max_length=44)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum aangemaakt"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Hallo",
                        help_text="Schrijf hier je bericht. Maximaal 3000 karakters",
                        max_length=3000,
                        verbose_name="Bericht",
                    ),
                ),
                ("nonce", models.CharField(max_length=64)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum aangemaakt"
                    ),
                ),
                (
                    "date_changed",
                    models.DateTimeField(null=True, verbose_name="Datum bewerkt"),
                ),
                (
                    "chatroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chatroomcreating.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
