# Generated by Django 5.1.3 on 2025-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatroomcreating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="secret_key",
            field=models.CharField(
                default="u4Rz1A9m3qfZT8c2gL9HtJKdq6yMx1C+/XEV/8aI+0g=",
                editable=False,
                max_length=44,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(
                default="Hallo",
                help_text="Schrijf over je ervaringen. Alleen hallo wordt ook gewaardeerd",
                max_length=3000,
                verbose_name="Bericht",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=22,
                unique=True,
                verbose_name="Code om de chatroom te kunnen vinden",
            ),
        ),
    ]
