# Generated by Django 5.1.3 on 2025-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chatroomcreating",
            "0002_chatroom_secret_key_alter_chatmessage_body_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="nonce",
            field=models.CharField(default=30214, max_length=64),
            preserve_default=False,
        ),
    ]
