# Generated by Django 5.1.3 on 2025-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatroomcreating", "0003_chatmessage_nonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(
                default="Hallo",
                help_text="Schrijf hier je bericht. Maximaal 3000 karakters",
                max_length=3000,
                verbose_name="Bericht",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=10,
                unique=True,
                verbose_name="Code om de chatroom te kunnen vinden",
            ),
        ),
    ]
