# Generated by Django 5.1.3 on 2025-08-26 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatroomcreating", "0004_alter_chatmessage_body_alter_chatroom_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="name",
        ),
    ]
