# Generated by Django 5.0.4 on 2024-10-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gevoel volgens geweldloze communicatie, waaruit de gebruiker kan kiezen voor het maken van een bericht', max_length=50, verbose_name='Gevoel')),
                ('isFullfilledNeed', models.BooleanField(help_text='Geweldloze communicatie deelt gevoelens in in gevoelens bij vervulde behoeften en gevoelens bij niet-vervulde behoeften. Is dit een gevoel bij een vervulde behoefte?', verbose_name='is Gevoel bij vervulde behoefte?')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nvc.feeling', verbose_name='Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Behoefte volgens geweldloze communicatie, waaruit de gebruiker kan kiezen voor het maken van een bericht', max_length=50, verbose_name='Behoefte')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nvc.need', verbose_name='Categorie')),
            ],
        ),
    ]
