# Generated by Django 5.0.4 on 2024-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='isFullfilledNeed',
            field=models.BooleanField(default=True, help_text='Geweldloze communicatie deelt gevoelens in in gevoelens bij vervulde behoeften en gevoelens bij niet-vervulde behoeften. Is dit een gevoel bij een vervulde behoefte?', verbose_name='is Gevoel bij vervulde behoefte?'),
        ),
    ]
