# Generated by Django 5.0.4 on 2024-10-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc', '0002_alter_feeling_isfullfilledneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nvc.feeling', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nvc.need', verbose_name='Categorie'),
        ),
    ]
