# Generated by Django 5.2.7 on 2025-12-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optioneel bericht (max 500 tekens)",
                        max_length=500,
                        verbose_name="Persoonlijk bericht",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In afwachting"),
                            ("accepted", "Geaccepteerd"),
                            ("rejected", "Afgewezen"),
                            ("cancelled", "Geannuleerd"),
                            ("expired", "Verlopen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Verzoek verloopt automatisch na 14 dagen",
                        verbose_name="Verloopt op",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_partnership_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verzonden door",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_partnership_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ontvangen door",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnerverzoek",
                "verbose_name_plural": "Partnerverzoeken",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="StreetPartnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_interaction",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Laatste interactie"
                    ),
                ),
                (
                    "show_moments",
                    models.BooleanField(
                        default=True, verbose_name="Toon momenten aan elkaar"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Actief partnerschap"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Beëindigd op"
                    ),
                ),
                (
                    "partnership_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="streetpartner.partnershiprequest",
                        verbose_name="Origineel verzoek",
                    ),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_partnerships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gebruiker 1",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_partnerships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gebruiker 2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Straatpartnerschap",
                "verbose_name_plural": "Straatpartnerschappen",
                "ordering": ["-last_interaction"],
                "unique_together": {("user1", "user2")},
            },
        ),
    ]
