# Generated by Django 5.1.3 on 2025-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("number", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("hasCanceled", models.BooleanField(default=False)),
            ],
        ),
    ]
