name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest
      # You may pin to the exact commit or the version.
      # uses: pavelzw/pytest-action@c9e5b9c8d93290ff47dcf6a28c6b19ca0b42e487
      uses: pavelzw/pytest-action@v2.1.0
      with:
        # Print a GitHub job summary
        job-summary: # optional, default is true
        # Verbose output
        verbose: # optional, default is true
        # Use emojis in the output
        emoji: # optional, default is true
        # Custom arguments to pass to pytest
        custom-arguments: # optional, default is 
        # Custom command to replace the `pytest` call. Can be a custom executable or something like `poetry run pytest` or `micromamba run -n myenv pytest`.
        custom-pytest: # optional, default is pytest
        # Title of the report
        report-title: # optional, default is Test Report
        # Add 'Click to expand' to the report
        click-to-expand: # optional, default is true
          
            
